# Config de treinamento apontando para o dataset em new_whales_rcnn/
project_root: "."
data:
  images:
    train_dir: "/data04/home/ppgmc/rlargolo/Dataset/dataset_splits/train/"
    val_dir: "/data04/home/ppgmc/rlargolo/Dataset/dataset_splits/val/"
    test: "/data04/home/ppgmc/rlargolo/Dataset/dataset_splits/test/"
  annotations:
    train_json: "/data04/home/ppgmc/rlargolo/Dataset/dataset_splits/train/annotations/instances.json"
    val_json: "/data04/home/ppgmc/rlargolo/Dataset/dataset_splits/val/annotations/instances.json"
    test_json: "/data04/home/ppgmc/rlargolo/Dataset/dataset_splits/test/annotations/instances.json"


training:
  epochs: 30
  batch_size: 2
  lr: 0.004
  momentum: 0.9
  weight_decay: 0.0005
  lr_step_size: 10
  lr_gamma: 0.5
  num_workers: 4
  seed: 42
  amp: true
  sample_vis_count: 4
  sample_vis_thresh: 0.1
  eval_map_every: 1
  transforms:
    hflip_p: 0.8
    use_iou_crop: true
    min_iou: 0.3
    short_sizes: [640, 800]
    max_size: 1333
    color_jitter: { p: 0.8, brightness: 0.35, contrast: 0.35, saturation: 0.25, hue: 0.03 }
    geom:
      rotation_deg: 8
      rotation_p: 0.5
      perspective: { p: 0.3, distortion_scale: 0.04 }
      zoom_out: { p: 0.4, side_range: [1.0, 1.6], fill: 0 }
    photometric:
      photometric_distort: { p: 0.5 }
      autocontrast_p: 0.2
      equalize_p: 0.1
      gaussian_blur: { p: 0.2, kernel_size: 3, sigma: [0.1, 1.2] }
      gaussian_noise: { p: 0.2, std: 0.01 }
    sanitize_boxes:
      enabled: true
      min_size: 1.0


model:
  name: "fasterrcnn_resnet50_fpn_v2"
  pretrained: yes
  num_classes: 2
  params:
    anchor_sizes: [[16], [32], [64], [128], [256]]
    rpn_pre_nms_top_n_train: 2000
    rpn_post_nms_top_n_train: 1000
    rpn_pre_nms_top_n_test: 1000
    rpn_post_nms_top_n_test: 50
    box_nms_thresh: 0.6
    box_detections_per_img: 300

output:
  dir: "outputs"
  experiment: "fasterrcnn_newDataset_080426"
  save_every: 1
  resume: "resume"

early_stopping:
  enabled: true
  monitor: "val_loss"
  eval_map_every: 1
  mode: null
  min_delta: 0.0001
  patience: 10
  restore_best_weights: true
  prefer_val_mAP: true

cross_validation:
  enabled: false
  folds: 5
